---
title: "Package `jSDM` functionalities"
author: "Jeanne Clément"
date: "`r Sys.Date()`"
output:
  pdf_document :
    latex_engine : xelatex
    fig_caption : yes
    pandoc_args: ["--number-sections"]
header-includes: 
  - \usepackage{upgreek}
  - \usepackage{easybmat}
  - \usepackage{float}
  - \usepackage{fancyhdr}
  - \usepackage{hyperref}
  - \usepackage[frenchb]{babel}
  - \usepackage{amsmath,amssymb,amsthm}
  - \usepackage{graphicx}
  - \usepackage[labelfont=bf,textfont=sl,tableposition=top,small]{caption}
  - \usepackage{enumitem}
  - \usepackage{dsfont}
  - \usepackage{bbm}
  - \usepackage{answers}
  - \usepackage{xassoccnt}
bibliography: bib/biblio-jSDM.bib
---

# Abstract
- Benefits of JSDMs over SDMS
- Many packages available to adjust JSDMs but which have some limitations
- package jSDM optimised C++ routines to reduce compilation time and new functionalities : long format data, missing data, multiple visits by site, priors specification 
- Comparison of `Hmsc`, `boral` and  `jSDM` librairies compilation time, accuracy and predictive performance for fitting JSDMs on @Wilkinson2019 datasets
- Case-Study using a large Madagascar forest inventory, maps of biodiversity 
- Expected results : compilation time reduced, equivalent or better accuracy and predictive performance
- Discussion 

# Introduction

## State of the art
- Benefits of JSDMs over SDMs 

- Librairies for fitting JSDMs :
table to compare functionalities of jSDM, HMSC, s-jSDM, boral (JAGS), greta, gjam, BayesComm, STAN and gllvm (title Methods and software to fit joint species distribution models)

## Knowledge gap

- Limitations of existing librairies 
  * compilation time on large datasets
  * presence only data or presence absence data with multiple visits by site 
  * datasets with missing data 
  * spatialy explicit models 
  * specify mixed models with fixed or random species and site effects 
  * (taking into account species traits and phylogeny as explicative variables of the model)
  
## Response
- Implementation of `jSDM` package with optimised C++ code (Armadillo and GSL librairies)
  * Open source, new functionalities easy to implement, package évolutif 
  * new functionalities : fourth corner model, long format
  * lower compilation time
- Application on Madagascar forest inventories, current (and future) climate conditions (and species traits datasets)
   
# Methods

## The structure of the jSDM problem

- GLMM and LVM @Warton2015

- models definition 
  * link function : probit, logit, log 
  * data type : presence/absence, presence/absence with multiple visits by site, abundance 
  * data format : wide and long format
  * mixed models with random or fixed site and species effect 
  * fourth corner models including species traits

## Current approaches to fit the jSDM model structure

- GLMM and LVM ($\Sigma = \Lambda \Lambda^{\prime}$) @Warton2015
- Bayesian inference method : 
  * priors specification 
  * Gibbs sampling using conjugate prior formula (probit link function)
  * Metropolis-Hastings algorithm (logit and log link function)
  
## Benchmarking our method against state-of-the-art jSDM implementation
- datasets @Wilkinson2019
- n.mcmc, compilation time, deviance 
- compute AUC to assess the predictive performance of the models

##  Case study - Inference of biodiversity maps in Madagascar from forest inventories
### Datasets 
#### Forest inventory
#### Current environmental variables
### Fitting joint species distribution model (JSDM) 
#### Model definition
#### Parameters inference
#### Evaluation of MCMC convergence

### Evaluation of predictive performance
- compute AUC on inventory sites to assess the predictive performance of the model

### Computation of species-species associations

### Interpolation of parameters between inventory sites 
- GRASS + rgrass7 
- Regularized splines with tension (RST) @Mitasova1993

### Species richness computation 
- use thresholds which maximize TSS to get presence/absence maps from occurence probabilities maps  
- sum presence/absence maps to get species richness estimation

### Species turnover computation 
- PCA for each pixel of the presence/absence maps (@Allnutt2008)
- coordinates on the first 3 axes of the PCA reflect the composition of the species community likely to occupy the corresponding pixel
- coordinates scaled to $[0.255]$ so that they can be represented by red colour levels for the first axis, green for the second and blue for the third
- on resulting $\beta$ diversity map a colour difference between two pixels indicates that the species present are not the same, while pixels of identical colour host communities of similar species. 

# Results 

## Method validation and benchmark against state-of-the-art jSDMs

Table comparison HMSC, boral, jSDM on @Wilkinson2019 datasets + birds + mites + aravo (traits) + simulated dataset n.mcmc, compilation time, deviance, predictive performance (TSS or AUC) + RMSE on simulated dataset 

### Computational speed

### Accuracy of the inference about species-environment and species-species associations
comparison of TSS and RMSE obtained with differents libraries 

### Predicting species occurrences
comparison of AUC obtained with differents libraries

## Case study - Inference of biodiversity maps in Madagascar from forest inventories

### Predictive performance of the model 
- compute AUC on inventory sites 

### Estimated species-species associations

### Estimated species richness on inventory sites

### Estimated species richness at Madagascar scale

### Estimated species turnover at Madagascar scale

# Discussion
## Other software comparison

Computational performance :

Inferential performance :

jSDM advantages : 
- lower compilation time than most other softwares
- Open source
- new functionalities easy to implement (evolutive package)
- complete documentation

## Limitation of jSDM and perspective
- very large dataset still too long fitting, sjSDM usefull in this case 
- phylogeny
- spatially explicit models
- presence only data

## Implications and outlook for ecological data analysis
- to predict species distributions area 
- to estimate species diversity ($\alpha$), species turnover ($\beta$) or other diversity indices
- to predict the evolution of biodiversity under climate change
- to identify refuge zone of biodiversity 
- to explain difference of vulnerability to climate change between species in relation to their functional traits

# Acknowledgments

# Data Accessibility

# References